### Compute the bond angles for methane
Methane bond angles are formed by the combination H-C-H. Taking C atom as the centroid of the a tetrahedron woth vertices (1,0,0), (0,1,0), (0,0,1) and (1,1,1) then the centroid is (0.5,0.5,0.5). Each of the vertices corresponds to a hydrogen atom 

In [24]:
import numpy as np
import numpy.linalg as LA
import math

In [25]:
def nCr(n,r):
    """Compute number of combinations"""
    f = math.factorial
    return f(n) // f(r) // f(n-r)

In [26]:
def get_bond_angles(centroid, vertices):
    
    bond_vectors = vertices - centroid
    bond_lenght = LA.norm(bond_vectors, axis=-1)

    print(bond_vectors, '\n')

    ii = bond_vectors.shape[0]
    
    m = nCr(bond_vectors.shape[0], 2)
    angles = np.zeros((m,1))
    
    k = 0
    for i in range(ii - 1):
        for j in range(i + 1, ii):
            angle = np.degrees(np.arccos(np.dot(bond_vectors[i, :], bond_vectors[j, :]) / (bond_lenght[i] * bond_lenght[j])))
            angles[k] = angle
            k += 1
            print("Angle between {} and {} is: {:.2f}".format(bond_vectors[i, :],
                                                         bond_vectors[j, :],
                                                         angle))
    k += 1
    
    return angles

In [27]:
centroid = np.array([0.5,0.5,0.5])
vertices = np.array([[1,0,0],
                     [0,1,0],
                     [0,0,1],
                     [1,1,1]])

angles = get_bond_angles(centroid, vertices)

[[ 0.5 -0.5 -0.5]
 [-0.5  0.5 -0.5]
 [-0.5 -0.5  0.5]
 [ 0.5  0.5  0.5]] 

Angle between [ 0.5 -0.5 -0.5] and [-0.5  0.5 -0.5] is: 109.47
Angle between [ 0.5 -0.5 -0.5] and [-0.5 -0.5  0.5] is: 109.47
Angle between [ 0.5 -0.5 -0.5] and [0.5 0.5 0.5] is: 109.47
Angle between [-0.5  0.5 -0.5] and [-0.5 -0.5  0.5] is: 109.47
Angle between [-0.5  0.5 -0.5] and [0.5 0.5 0.5] is: 109.47
Angle between [-0.5 -0.5  0.5] and [0.5 0.5 0.5] is: 109.47


In [28]:
print(angles.shape)
angles

(6, 1)


array([[109.47122063],
       [109.47122063],
       [109.47122063],
       [109.47122063],
       [109.47122063],
       [109.47122063]])

In [ ]:
# Compute mean angle for each atom with at least two bonds
n_centroid_atoms = count_atoms_with_n_bonds(1)
centroid_mean_angle = np.zeros((n_centroid_atoms,2))

i = 0
for atom, neighbors in mol_graph.adjacency(): #adjacency returns an iterator for the neighbors

    atom_names = [mol_graph.nodes[atom]['atom_name']]  # List with atom names
    centroid = np.array(mol_graph.nodes[atom]['coordinates'])
    n_neighbors = len(list(neighbors))
      
    if n_neighbors > 1:

        vertices = np.zeros((n_neighbors, 3))
        for j, nbr_atom in enumerate(list(neighbors)):
            vertices[j, :] = np.array(mol_graph.nodes[nbr_atom]['coordinates'])
            atom_names.append(mol_graph.nodes[nbr_atom]['atom_name'])

        angles = get_bond_angles(centroid, vertices, atom_names, verbose=True)
        centroid_mean_angle[i, 0] = atom
        centroid_mean_angle[i, 1] = np.mean(angles)

    else:
        continue

    print('---------')
    i += 1