In [1]:
%matplotlib inline
import networkx as nx
import numpy as np
import numpy.linalg as LA
import matplotlib.pyplot as plt 

## Getting Bond lenghts

In [9]:
# Compute the distance between pairs of atoms

ba = np.array([[0,1],[0,2],[0,3]])
co = np.array([[1.84669995, 2.76379991, 8.36610031],
             [1.94828415, 2.72273469, 8.41565132],
             [1.78098989, 2.66380095, 8.35718346],
             [1.80249786, 2.82200766, 8.46192265]])


#ba = np.array([[0,1],[2,3]])
#co = np.array([[0, 0, 0],
#             [2, 3, 5],
#             [2, -1, 7],
#             [1,-3, 5]])

print(ba.shape)
# Initialize distance array
dis = np.zeros(ba.shape[0])

coords_between_bonded_atoms = co[ba]
bond_vectors = np.diff(coords_between_bonded_atoms, axis=1)

dis = LA.norm(bond_vectors, axis=-1)

bond_unit_vectors = np.divide(bond_vectors, dis[:,np.newaxis])

unit_dis = LA.norm(bond_unit_vectors, axis=-1)


print('Bonded atoms \n')
print(ba)
print('-------------\nCoordinates\n')
print(co, '\n')
print(co.shape)
print('-------------\nCoordinates between pairs of atoms\n')
print(coords_between_bonded_atoms, '\n')
print(coords_between_bonded_atoms.shape)
print('-------------\nBond Vectors\n')
print(bond_vectors)
print(bond_vectors.shape, '\n')
print('-------------\nVector Norm\n')
print(dis)
print(dis.shape, '\n')
print('-------------\nUnit Vectors\n')
print(bond_unit_vectors)
print(bond_unit_vectors.shape, 'Unit vectors norm\n')
print(unit_dis)

(2, 2)
Bonded atoms 

[[0 1]
 [2 3]]
-------------
Coordinates

[[ 0  0  0]
 [ 2  3  5]
 [ 2 -1  7]
 [ 1 -3  5]] 

(4, 3)
-------------
Coordinates between pairs of atoms

[[[ 0  0  0]
  [ 2  3  5]]

 [[ 2 -1  7]
  [ 1 -3  5]]] 

(2, 2, 3)
-------------
Bond Vectors

[[[ 2  3  5]]

 [[-1 -2 -2]]]
(2, 1, 3) 

-------------
Vector Norm

[[6.164414]
 [3.      ]]
(2, 1) 

-------------
Unit Vectors

[[[ 0.32444284  0.48666426  0.81110711]]

 [[-0.33333333 -0.66666667 -0.66666667]]]
(2, 1, 3) Unit vectors norm

[[1.]
 [1.]]


In [2]:
def compute_norm(v):
    """Computes the norm of a vector"""
    norm = np.sqrt(np.dot(v, v))
    return norm

#### Another way to get bong lenghts

In [4]:
ba = np.array([[0,1],[0,2],[0,3]])
co = np.array([[1.84669995, 2.76379991, 8.36610031],
             [1.94828415, 2.72273469, 8.41565132],
             [1.78098989, 2.66380095, 8.35718346],
             [1.80249786, 2.82200766, 8.46192265]])

coords_between_bonded_atoms = co[ba]

def distance_between_two_points(p1, p2):
    # Get distance between two points in 3D space
    x1 = p1[0]
    y1 = p1[1]
    z1 = p1[2]
    x2 = p2[0]
    y2 = p2[1]
    z2 = p2[2]
    
    distance = np.sqrt((x2 - x1)**2 + (y2 - y1)**2 + (z2 - z1)**2)
    return distance
    

for i in range(coords_between_bonded_atoms.shape[0]):
    p1 = coords_between_bonded_atoms[i, 0, :]
    p2 = coords_between_bonded_atoms[i, 1, :]
    d = distance_between_two_points(p1, p2)
    print(d)


0.12025391708925127
0.1199879752317192
0.1205150935090962


## Getting Angles Between Vectors

In [7]:
ba = np.array([[0,1],[0,2],[1,2]])
#co = np.array([[4, 0, 7],
#             [-2, 1, 3],
#             [3, 4, -7]])
co = np.array([[1.84669995, 2.76379991, 8.36610031],
             [1.94828415, 2.72273469, 8.41565132],
             [1.78098989, 2.66380095, 8.35718346],
             [1.80249786, 2.82200766, 8.46192265]])

# Initialize distance array
bond_angles = np.zeros(ba.shape[0])
coords_between_bonded_atoms = co[ba]


for i in range(coords_between_bonded_atoms.shape[0]):
    
    unit_vector_1 = coords_between_bonded_atoms[i, 0, :] / LA.norm(coords_between_bonded_atoms[i, 0, :])
    unit_vector_2 = coords_between_bonded_atoms[i, 1, :] / LA.norm(coords_between_bonded_atoms[i, 1, :])
    
    bond_angles[i] = np.degrees(np.arccos(np.dot(unit_vector_1, unit_vector_2)))

bond_angles = bond_angles.reshape((bond_angles.shape[0], -1))

print('Bonded atoms \n')
print(ba)
print('-------------\nCoordinates\n')
print(co, '\n')
print(co.shape)
print('-------------\nCoordinates between pairs of atoms\n')
print(coords_between_bonded_atoms, '\n')
print(coords_between_bonded_atoms.shape)
print('-------------\nVector norms\n')
print(unit_dis)
print(unit_dis.shape, '\n')
print('-------------\nBond Angles\n')
print(bond_angles)
print(bond_angles.shape, '\n')

Bonded atoms 

[[0 1]
 [0 2]
 [1 2]]
-------------
Coordinates

[[1.84669995 2.76379991 8.36610031]
 [1.94828415 2.72273469 8.41565132]
 [1.78098989 2.66380095 8.35718346]
 [1.80249786 2.82200766 8.46192265]] 

(4, 3)
-------------
Coordinates between pairs of atoms

[[[1.84669995 2.76379991 8.36610031]
  [1.94828415 2.72273469 8.41565132]]

 [[1.84669995 2.76379991 8.36610031]
  [1.78098989 2.66380095 8.35718346]]

 [[1.94828415 2.72273469 8.41565132]
  [1.78098989 2.66380095 8.35718346]]] 

(3, 2, 3)
-------------
Vector norms

[[1.]
 [1.]
 [1.]]
(3, 1) 

-------------
Bond Angles

[[0.67883634]
 [0.69078964]
 [0.97526873]]
(3, 1) 



In [21]:
coords_between_bonded_atoms[1, 0, 0:2]

array([1.84669995, 2.76379991])

### Map an array to anothers index

In [4]:
import molsysmt as msm

molecular_system_2 = msm.convert('1NCR', 'molsysmt.MolSys')
molecular_system_2 = msm.remove_solvent(molecular_system_2, water=True, ions=True)
molecular_system_2 = msm.add_missing_hydrogens(molecular_system_2, pH=7.4)

indices, names, bonded_atoms, coords = msm.get(molecular_system_2, selection='entity_name=="W11"', target="atom", 
                                           atom_index=True, name=True, inner_bonded_atoms=True, coordinates=True)

print(indices)
print(indices.shape)

print(bonded_atoms, '\n')
print(bonded_atoms.shape)

/Users/danielibarrola/Documents/molsys/MolSys_v0.1/MolSysMT/molsysmt/native/io/topology/classes/mmtf_MMTFDecoder.py:43: UserWarning: The structure in the PDB has biological assemblies. There are geometrical transformations proposed in the structure. See the following issue in the source code repository: https://github.com/uibcdf/MolSysMT/issues/33
  warnings.warn(warning_message)


[12496 12497 12498 ... 12520 12521 12522]
(27,)
[[12497 12496]
 [12498 12497]
 [12499 12498]
 ...
 [12520 12518]
 [12521 12518]
 [12522 12518]] 

(29, 2)


In [6]:
map_dict = {value:index for index,value in enumerate(indices)} #dictionary with keys as the array value and values as the array index
map_dict

{12496: 0,
 12497: 1,
 12498: 2,
 12499: 3,
 12500: 4,
 12501: 5,
 12502: 6,
 12503: 7,
 12504: 8,
 12505: 9,
 12506: 10,
 12507: 11,
 12508: 12,
 12509: 13,
 12510: 14,
 12511: 15,
 12512: 16,
 12513: 17,
 12514: 18,
 12515: 19,
 12516: 20,
 12517: 21,
 12518: 22,
 12519: 23,
 12520: 24,
 12521: 25,
 12522: 26}

In [11]:
from numpy import copy

newArray = copy(bonded_atoms)
for k, v in map_dict.items(): newArray[bonded_atoms==k] = v
    
newArray

array([[ 1,  0],
       [ 2,  1],
       [ 3,  2],
       ...,
       [24, 22],
       [25, 22],
       [26, 22]])

### Computing direction cosines

In [16]:
ba = np.array([[0,1],[0,2],[0,3]])
co = np.array([[1.84669995, 2.76379991, 8.36610031],[1.94828415, 2.72273469, 8.41565132],[1.78098989, 2.66380095, 8.35718346],[1.80249786, 2.82200766, 8.46192265]])

# ba = np.array([[0,1],[2,3]])
# co = np.array([[0, 0, 0],[1, 2, 3],[0, 0, 0],[2, 4, 4]])

# Initialize distance array
dis = np.zeros(ba.shape[0])
coords_between_bonded_atoms = co[ba]
bond_vectors = np.diff(coords_between_bonded_atoms, axis=1)
dis = LA.norm(bond_vectors, axis=-1)
cosines = np.divide(bond_vectors,dis[:, np.newaxis])
angles = np.degrees(np.arccos(cosines))

print(bond_vectors)
print('\n------------------')
print(cosines)
print('\n------------------')
print(angles)

[[[ 0.1015842  -0.04106522  0.04955101]]

 [[-0.06571006 -0.09999896 -0.00891685]]

 [[-0.04420209  0.05820775  0.09582234]]]

------------------
[[[ 0.84474753 -0.34148759  0.41205319]]

 [[-0.54763871 -0.83340818 -0.07431453]]

 [[-0.36677638  0.48299137  0.79510655]]]

------------------
[[[ 32.35510361 109.96753186  65.66612167]]

 [[123.20516896 146.45044898  94.26183786]]

 [[111.51694526  61.11904401  37.33467946]]]


In [18]:
## For loop to compare or compute between each pair of elements in an array

In [17]:
for i in range(3):
    for j in range(i + 1, 3 + 1):
        print('i: ', i)
        print('j + 1: ', j)
    print('----')

i:  0
j + 1:  1
i:  0
j + 1:  2
i:  0
j + 1:  3
----
i:  1
j + 1:  2
i:  1
j + 1:  3
----
i:  2
j + 1:  3
----
